@startuml

title "Register User (UML Sequence Diagram)"
header By PlantUML (timo)

actor User as User

box "Browser" #LightGreen
participant AppUI as AppUI
end box

box "REST Service" #LightBlue
participant SparkJava as SparkJava
participant AuthService as AuthService
participant Neo4JDriver as Neo4JDriver
participant Neo4JSession as Neo4JSession
end box

database Neo4JGraphDB as Neo4JGraphDB

User -> AppUI: Submit \nregistration page
AppUI -> SparkJava: /auth/register\nname,email
SparkJava -> AuthService : register()
AuthService -> AuthService : Check email \nis unique

alt#Red #LightPink Failure

AuthService --> SparkJava : Error: \nAccount exists!
SparkJava --> AppUI: Error: \nAccount exists!
AppUI --> User: Response \nError: Account exists!

else #LightBlue Continue

AuthService -> AuthService : encrypt plain password
AuthService -> Neo4JDriver : session()
activate Neo4JSession
Neo4JDriver-->AuthService : <<session activated>>

AuthService -> Neo4JSession : writeTransaction(Cypher_Query)
Neo4JSession -> Neo4JGraphDB: Request(Cypher_Query)

alt#Red #LightPink Failure

Neo4JGraphDB --> Neo4JSession: ConstraintViolation (email)
Neo4JSession --> AuthService:  ConstraintViolation (email)

AuthService --> SparkJava : Error: \nAccount exists!
SparkJava --> AppUI: Error: \nAccount exists!
AppUI --> User: Response \nError: Account exists!

else #LightBlue Continue
Neo4JGraphDB -> Neo4JGraphDB: Adds User Node \nand generates UUID
Neo4JGraphDB --> Neo4JSession: Response with userId
Neo4JSession --> AuthService:  Response(userId,)
deactivate Neo4JSession
AuthService -> AuthService : Generate Bearer Token
AuthService -> AuthService : Cache Token
AuthService --> SparkJava : <<token,userId,\nemail,name>>
SparkJava --> AppUI: JSON-Response(token,\nuserId,email,name)
AppUI --> User: Response: \nSuccess

end
end

@enduml
